enum CategoryIcon {
  ACCOMMODATION = 'ACCOMMODATION',
  ENTERTAINMENT = 'ENTERTAINMENT',
  GROCERIES = 'GROCERIES',
  HEALTHCARE = 'HEALTHCARE',
  INSURANCE = 'INSURANCE',
  RENT_CHARGE = 'RENT_CHARGE',
  RESTAURANTS_BARS = 'RESTAURANTS_BARS',
  SHOPPING = 'SHOPPING',
  TRANSPORT = 'TRANSPORT',
  OTHER = 'OTHER',
}

export default CategoryIcon;
